config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :fancy_menu_settings do
    	post :save, :on => :member
    end
  end
end

app/models/spree/fancy_menu_item.rb
class Spree::FancyMenuItem < ActiveRecord::Base
  belongs_to :taxon, :class_name => 'Spree::Taxon'

  validates :name, :index, :depth, :presence => true
  validates :index, :uniqueness => true
  validates :index, :numericality => { :only_integer => true, 
  	                                   :greater_than_or_equal_to => 0 }
  validates :depth, :numericality => { :only_integer => true, 
  									   :greater_than_or_equal_to => 1, 
  									   :less_than_or_equal_to => 3 }
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_one :fancy_menu_item, :dependent => :destroy
end

app/controllers/spree/admin/fancy_menu_settings_controller.rb
module Spree
  module Admin
    class FancyMenuSettingsController < Spree::Admin::BaseController

      def edit
        @taxonomies = Spree::Taxonomy.all
        @menu_items = Spree::FancyMenuItem.includes(:taxon).all
      end
      
      def save
        begin
          FancyMenuItem.transaction do

            @errors = { :base => [] }

            begin
              FancyMenuItem.destroy_all
            rescue Exception => e
              @errors[:base] << e.to_s
              raise
            end

            if params[:menu]

              if params[:menu].count > 10
                @errors[:base] << "The count of items on the menu must be less than 10"
                raise
              end

              params[:menu].each do |fancy_item|
                name = fancy_item[:name].chomp.reverse!.chomp.reverse!
                item = Spree::FancyMenuItem.create(:name => name,
                                                 :index => fancy_item[:index],
                                                 :depth => fancy_item[:depth],
                                                 :taxon_id => fancy_item[:id])
                if !item.save
                  @errors[:base] << "There were some errors with the menu items validation"
                  raise
                end
              end
            end

            redirect_to "/"
          end
        rescue
          @taxonomies = Spree::Taxonomy.all
          @menu_items = Spree::FancyMenuItem.includes(:taxon).all
          render :edit
        end
      end

    end
  end
end

app/helpers/spree/admin/fancy_menu_settings_helper.rb
module Spree
	module Admin
		module FancyMenuSettingsHelper
			
			def have_children(taxon_id)
				taxon = Taxon.find(taxon_id)
				return taxon.children.count != 0
			end

			def get_children(taxon_id)
				taxon = Taxon.find(taxon_id)
				return taxon.children
			end
			
			def get_taxon_depth(taxon_id)
				return 5
			end

			def on_menu(menu, taxon)
				menu.each do |item|
					if item.taxon.id == taxon.id
						return true
					end
				end
				return false
			end

			def root(taxonomy_id)
		  	return Taxon.find_by_taxonomy_id(taxonomy_id)
		  end

		end
	end
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.module_eval do

	def fancy_menu?()
		Spree::FancyMenuItem.any?
	end

  def fancy_breadcrumbs?(taxon)
    return taxon && taxon.ancestors.any?
  end

	def set_fancy_menu(options = {})
		items = []
		Spree::FancyMenuItem.all.each do |fi|
			items << Spree::Taxon.find(fi.taxon_id)
		end
		items
	end

	def set_fancy_breadcrumbs(taxon_id, options = {})
		Spree::Taxon.find(taxon_id).ancestors
	end

  def fancy_item_link(taxon, taxon_selected)
  	css_class = "menu-item-link" 
  	if taxon_selected && taxon.name == taxon_selected.name
  		css_class << " menu-item-link-active" 
  	end
  	link_to content_tag(:span, taxon.name, :class => "menu-item-text"), set_fancy_item_link(taxon.permalink), :class => css_class
  end

  def set_fancy_item_link(permalink)
  	"/t/" << permalink
  end

  def need_render?(depth, taxon)
    taxon.reload
    depth < 3 && taxon.children.any?
  end

end

app/views/spree/admin/fancy_menu_settings/_errors.html.erb
<div id="errors">

	<ul id="list-errors">

		<li>Errors:<span id="msg"> (The menu has ben reset to the last stable update)</span></li>

		<% @errors[:base].each do |e| %>
			<li><%= e %></li>
		<% end %>
		
	</ul>
	
</div>

app/views/spree/admin/fancy_menu_settings/_inplace.html.erb
<script>

	$().ready(function(){
		
		$('#sortable_menu').sortable({
	    	placeholder: "ui-state-highlight", 
	    	stop: function(event, ui){}
  		});
  		$('#sortable_menu').disableSelection();
		
		$('.slide-list').hide();
		$('.slide-trigger').click(function() {
			icon_tool = $(this).find('i').first();
  			$(this).next().slideToggle('fast', function() {
  				if($(icon_tool).attr('class') == 'icon-chevron-down')
  					$(icon_tool).attr('class', 'icon-chevron-up');
  				else
  					$(icon_tool).attr('class', 'icon-chevron-down');
  			});
		});
		
		$('.add-remove').click(function(event){
			if($(this).attr('data-state') == 'add')
				add_item($(this));
			else
				remove_item($(this));
			
			event.stopPropagation()
		});
		
		$('#button-collapse').click(function(){
			$('.slide-list').slideUp();
		});
		
		$('#button-ready').click(function(){
			generate_form();
			$('#btn-menu-commit').click();
		});
		
		add_events_tree();
		generate_tab_width();		
		
	});

	function generate_tab_width(){
		leftMargin = 10
		$('ul').each(function(){
			depth = parseInt($(this).attr('data-d'));
			$(this).css('margin-left', leftMargin * depth);
		});
	}
	
	function generate_form(){
	fields = '';
		$('#container-sortable-menu ul li').each(function(index){
			taxonomy_name = $(this).find('span').eq(1).text();
			taxonomy_id = $(this).attr('data-id');
			taxonomy_index = index;
			taxonomy_depth = $(this).find('input[id="depth_' + taxonomy_id + '"]').val();

			taxonomy_name_field = '<input name="menu[][name]" type="hidden" value="' + taxonomy_name + '" />';
			taxonomy_id_field = '<input name="menu[][id]" type="hidden" value="' + taxonomy_id + '" />';
			taxonomy_index_field = '<input name="menu[][index]" type="hidden" value="' + taxonomy_index + '" />';
			taxonomy_depth_field = '<input name="menu[][depth]" type="hidden" value="' + taxonomy_depth + '" />';
			
			fields += taxonomy_name_field + taxonomy_id_field + taxonomy_index_field + taxonomy_depth_field;
			
		});
		
		fields+= '<input id="btn-menu-commit" name="commit" type="submit" />';
		
		$('#form-fields').html(fields);
	}
	
	function add_events_tree(){
		$('.li-element a i').hover( 
      function () { 
        $(this).addClass('icont-black'); 
      },  
      function () { 
        $(this).removeClass('icont-black');
      } 
    );
	}

	function remove_item(element){
		name = element.parent().parent().attr('data-name');
		id = element.parent().parent().attr('data-id');
		
		$('#sortable_menu').children("[data-id=" + id + "]").remove()
		
		item = '#' + name;
		$(item).children('a').attr('data-state', 'add');
		$(item).children('a').html('<i class="icont-plus"></i>');
		
		add_events_tree();
	}

	function add_item(element){
		name = element.parent().parent().attr('data-name');
		id = element.parent().parent().attr('data-id');
		
		$('#sortable_menu').append('<li data-id="'+ id +'"><span><i class="icon-move"></i></span><span>' + name + '</span><span><input id="depth_'+ id +'" max="3" min="1" name="depth_'+ name +'" type="number" value="1" /></span></li>');
		
		item = '#' + name;
		$(item).children('a').attr('data-state', 'remove');
		$(item).children('a').html('<i class="icont-minus"></i>');
		
		add_events_tree();
	}
</script>

app/views/spree/admin/fancy_menu_settings/_list.html.erb
<ul data-d="<%= d %>">

<% taxons.each do |taxon| %>
	
	<li data-name="<%= taxon.name %>" data-id="<%= taxon.id %>">
		
		<p id="<%= taxon.name %>" class="slide-trigger">

			<span class="icon-list-taxon">
              <i class="icon-chevron-down"></i>
            </span>

			<span class="li-element-text">
              <%= taxon.name %>
            </span>
          <% if on_menu(@menu_items, taxon)%>
              <a class="add-remove" data-state="remove">
                <i class="icont-minus"></i>
              </a>
          <% else %>
              <a class="add-remove" data-state="add">
                <i class="icont-plus"></i>
              </a>
          <% end %>

		</p>
	
		<div class="slide-list">
			
			<% if have_children(taxon.id) %>
				<%= render :partial => 'list', :locals => { :taxons => get_children(taxon.id), :d => d + 1 } %>
			<% end %>

		</div>

	</li>

<% end %>

</ul>

app/views/spree/admin/fancy_menu_settings/_menu_preview.html.erb
<div id="container-sortable-menu">
  <ul id="sortable_menu">
    <% if @menu_items.count > 0 %>
      <% @menu_items.each do |item| %>
        <li data-id="<%= item.taxon.id %>">
          <span>
            <i class="icon-move"></i>
          </span>
          <span>
            <%= item.name %>
          </span>
          <span>
            <input id="depth_<%= item.taxon.id %>" max="3" min="1" name="depth_<%= item.name %>" type="number" value="<%= item.depth %>" />
          </span>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="clear"></div>
</div>

app/views/spree/admin/fancy_menu_settings/_roots.html.erb
<ul data-d="<%= d %>">

<% taxonomies.each do |taxonomy| %>
	
	<% taxon = root(taxonomy.id) %>
	<li data-name="<%= taxon.name %>" data-id="<%= taxon.id %>">
		
		<p id="<%= taxon.name %>" class="li-element slide-trigger">

			<span class="icon-list-taxon">
              <i class="icon-chevron-down"></i>
            </span>

			<span class="li-element-text">
              <%= taxon.name %>
            </span>
          <% if on_menu(@menu_items, taxon)%>
              <a class="add-remove" data-state="remove">
                <i class="icont-minus"></i>
              </a>
          <% else %>
              <a class="add-remove" data-state="add">
                <i class="icont-plus"></i>
              </a>
          <% end %>

		</p>
	
		<div class="slide-list">
			
			<% if have_children(taxon.id) %>
				<%= render :partial => 'list', :locals => { :taxons => get_children(taxon.id), :d => d + 1 } %>
			<% end %>

		</div>

	</li>

<% end %>

</ul>

app/views/spree/admin/fancy_menu_settings/current.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<ul>
<% @testlist.each do |item| %>
	<li><%= item[:name] %>,<%= item[:id] %>,<%= item[:index] %>,<%= item[:depth] %></li>
<% end %>
</ul>

app/views/spree/admin/fancy_menu_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%=t(:menu_configuration)%>
<% end %>

<%= render :partial => 'inplace' %>

<% if @errors %>
  <%= render :partial => 'errors' %>
<% end %>

<%= render :partial => 'menu_preview' %>

<%= button_tag(:type => 'button', :id => "button-collapse") do %>
    <i class="icont-circle-arrow-up"></i>
<% end %>

<div id="taxons-tree">
	<%= render(:partial => 'roots', :locals => { :taxonomies => @taxonomies, :d => 0 }) %>
</div>

<div id="admin-fancy-menu-controls">
	<%= button_tag(:type => 'button', :id => "button-ready") do %>
    <i class="icon-thumbs-up"></i>
  	<span>Ready</span>
  <% end %>
</div>

<div id="admin-fancy-menu-form">
	<%= form_tag(save_admin_fancy_menu_settings_path()) do %>
    <div id="form-fields"></div>
  <% end %>
</div>

app/views/spree/admin/fancy_menu_settings/save.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<ul>
<% @testlist.each do |item| %>
	<li><%= item[:name] %>,<%= item[:id] %>,<%= item[:index] %>,<%= item[:depth] %></li>
<% end %>
</ul>

app/views/spree/shared/_set_fancy_menu.html.erb
<% if fancy_menu? %>
    <div class="clear-fancy"></div>
    <%= render(:partial => 'spree/shared/set_fancy_menu_inplace') %>
    <nav id="user-fancy-menu" data-hook="header-user-fancy-menu">
      <div id="fancy-container">
        <% if fancy_breadcrumbs?(@taxon) %>
          <div id="fancy-breadcrumbs-wrapper" class="fancy-width">
            <ul id="fancy-breadcrumbs" data-hook="header-user-fancy-menu-breadcrumbs">
              <% set_fancy_breadcrumbs(@taxon.id).each do |item| %>
                <li>
                  <a href="<%= set_fancy_item_link(item.permalink) %>">
                    <span class="breadcrumbs-item-text">
                      <%= item.name %>
                    </span>
                    <span class="divider">/</span>
                  </a>
                </li>
              <% end %>
              <li id="breadcrumbs-item-selected"><%= @taxon.name %></li>
            </ul>
            <div class="clear-fancy"></div>
          </div>
        <% end %>
        <div id="fancy-menu-wrapper" class="fancy-width">
          <ul id="fancy-menu" data-hook="header-user-fancy-menu-menu">
            <% set_fancy_menu.each do |item| %>
              <li>
                <%= fancy_item_link(item, @taxon) %>
                <% if need_render?(0, item) %>
                <%= render(:partial => 'spree/shared/set_fancy_menu_dropdown_items', :locals => { :taxon => item, :depth => 1 }) %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <div class="clear-fancy"></div>
        </div>
      </div>
    </nav>
<% end %>

app/views/spree/shared/_set_fancy_menu_dropdown_items.html.erb
<ul id="depth-<%= depth %>">
	<% taxon.children.each do |item| %>
		<li>
			<% if item.children.any? %>
		     	<%= link_to(set_fancy_item_link(item.permalink), { :class => "menu-dropdown-item-link" }) do %>
		     		<span class="menu-dropdown-item-text">
		     			<%= item.name %>
			     		<i class="icon-chevron-right"></i>
		     		</span>
		    	<% end %>
		    <% else %>
		     	<%= link_to content_tag(:span, item.name, :class => "menu-dropdown-item-text"), set_fancy_item_link(item.permalink), :class => "menu-dropdown-item-link" %>
		    <% end %>
			<% if need_render?(depth, item) %>
				<%= render(:partial => 'spree/shared/set_fancy_menu_dropdown_items', :locals => { :taxon => item, :depth => depth + 1 }) %>
			<% end %>
		</li>
	<%end%>
</ul>

app/views/spree/shared/_set_fancy_menu_inplace.html.erb
<script>

	$().ready(function(){
		$("#fancy-menu li").hover(
		    function(){
		        $(this).children('ul').hide();
		        $(this).children('ul').slideDown('fast');
		    },
		    function () {
		        $('ul', this).hide();            
		    });
	});

</script>